# Generated by Django 5.1.4 on 2025-01-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedabadapp', '0002_contact_phone_contact_submit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='submit_date',
            new_name='submitted_at',
        ),
    ]
