# Generated by Django 5.1.4 on 2025-01-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedabadapp', '0003_rename_submit_date_contact_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='submitted_at',
        ),
    ]
