# Generated by Django 5.1.4 on 2025-01-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedabadapp', '0004_remove_contact_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
