# Generated by Django 5.1.4 on 2025-04-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedabadapp', '0005_remove_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='newspapers/')),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
