# Generated by Django 5.1.4 on 2025-05-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedabadapp', '0006_newspaper_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewspaperUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pdf_file', models.FileField(upload_to='uploads/pdfs/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='uploads/videos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Newspaper',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
