# Generated by Django 5.1.4 on 2025-05-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedabadapp', '0007_newspaperupload_delete_newspaper_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaperupload',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='newspaperupload',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
