# Generated by Django 5.1.4 on 2025-05-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedabadapp', '0008_alter_newspaperupload_pdf_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pdf', models.FileField(upload_to='newspapers/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.DeleteModel(
            name='NewspaperUpload',
        ),
    ]
