# Generated by Django 5.1.4 on 2025-05-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedabadapp', '0009_newspaper_video_delete_newspaperupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RemoveField(
            model_name='newspaper',
            name='pdf',
        ),
        migrations.AddField(
            model_name='newspaper',
            name='pdf_file',
            field=models.FileField(default=1, upload_to='uploads/pdfs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspaper',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/'),
        ),
    ]
