# Generated by Django 5.1.4 on 2025-05-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedabadapp', '0010_delete_video_remove_newspaper_pdf_newspaper_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pdfs/'),
        ),
    ]
