# Generated by Django 5.2.1 on 2025-05-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedabadapp', '0012_youtubevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='video_file',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
