# Generated by Django 5.2.1 on 2025-05-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedabadapp', '0013_youtubevideo_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
