# Generated by Django 5.2.1 on 2025-05-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedabadapp', '0015_alter_youtubevideo_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
